version: '3'

services:
  weatherapp-backend:
    build: ./backend
    ports:
      - 9000:9000
  
  weatherapp-frontend:
    build: ./frontend
    ports:
      - 8000:8000
    depends_on:
      - weatherapp-backend